#!/usr/bin/env php
<?php

array_shift($_SERVER['argv']);

$sourceDir  = __DIR__.'/src';
$source     = $sourceDir.'/tunnel';
$targetDir  = '/usr/local/bin';
$scripts    = $_SERVER['argv'] ?: array('php', 'phpunit');
$prefix     = 'v';
$color      = function($text) { return sprintf("\033[32m%s\033[0m", $text); };

foreach ($scripts as $script) {
    $link = $targetDir.'/'.$prefix.$script;

    printf("Setting up %s...", $color($link));

    @unlink($link);

    if (!symlink($source, $link)) {
        throw new \LogicException('Could not create symlink.');
    }

    printf("Done.\n");
}

