#!/usr/bin/env php
<?php

// `vphp` and `vphpunit` on the local system translate to `php` and `phpunit` in Vagrant
$prefix     = 'v';
$args       = $_SERVER['argv'];
$args[0]    = substr(basename($args[0]), strlen($prefix));

// Determine relative path from Vagrant root
$cwd        = getcwd();
$root       = $cwd;
$cmd        = join(' ', $args);

while ($root && $root !== '/' && !file_exists($root.'/Vagrantfile')) {
    $root = realpath($root.'/../');
}

// Ensure we're actually in a Vagrant project
if (!file_exists($root.'/Vagrantfile')) {
    throw new \InvalidArgumentException('Could not find `Vagrantfile` in `'.$cwd.'` or its parent directories.');
}

// Build Vagrant command
$relative       = str_replace($root, null, $cwd);
$shellCmd       = sprintf('cd .%s && %s', $relative, $cmd);
$vagrantCmd     = sprintf('vagrant ssh -c %s', escapeshellarg($shellCmd));

passthru($vagrantCmd);
